### ISSUE TITLE
add ability to open ocular on the most found page

### ISSUE THREAD

**Issue by PaulPruenster** [MatthiasEbner2002/pdf_search#3]
some key shoudl open the most found page in the pdf with the most resulds

ocular has a -p flag for opening it on a page

thanks

**Comment by MatthiasEbner2002** [comment]
oki doki

**Comment by MatthiasEbner2002** [comment]
After searching for the word in the PDFs, getting asked to open the PDF with the most occurrences, at the page of the first occurrence. PDF gets opened with ocular, and if already open, gets opened again. (there is still output of the ocluar command in the terminal after the program finished)
